# Generated by Django 2.1 on 2021-02-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('Profile_pic', models.ImageField(upload_to='facultyimages')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Exp', models.CharField(max_length=15)),
                ('qua', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=15)),
                ('Mobileno', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('DoB', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.City')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.State')),
            ],
            options={
                'verbose_name': 'Faculty',
            },
        ),
    ]
