# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='DoB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Exp',
            field=models.CharField(max_length=15, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dep',
            field=models.CharField(max_length=15, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qua',
            field=models.CharField(max_length=30, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.State', verbose_name='Sate name'),
        ),
    ]
