# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30, verbose_name='Book name')),
                ('author_name', models.CharField(max_length=30, verbose_name='Author name')),
                ('Book_image', models.ImageField(upload_to='Book_image/')),
                ('Edition', models.CharField(max_length=30, verbose_name='Edition')),
                ('Subject_name', models.CharField(max_length=10, verbose_name='Subject name')),
                ('review', models.CharField(max_length=30, verbose_name='Review')),
                ('upload_pdf', models.FileField(upload_to='uploadBook/')),
            ],
        ),
    ]
