# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='DoB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_number',
            field=models.IntegerField(verbose_name='Roll number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='a_number',
            field=models.CharField(max_length=10, verbose_name='Alt Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.State', verbose_name='State name'),
        ),
    ]
