# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30, verbose_name='Subject')),
                ('Practical_name', models.CharField(max_length=30, verbose_name='Practical name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student')),
            ],
        ),
    ]
