# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_name', models.CharField(max_length=30, verbose_name='Hostel name')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fees', models.CharField(max_length=3, verbose_name='Fees')),
                ('address', models.TextField(verbose_name='Address')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
