# Generated by Django 2.1 on 2021-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('Book_image', models.ImageField(upload_to='Book_image/')),
                ('Edition', models.CharField(max_length=30)),
                ('Subject_name', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=30)),
                ('upload_pdf', models.FileField(upload_to='uploadBook/')),
            ],
        ),
    ]
