# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=30, verbose_name='Subject name')),
                ('Sub_code', models.IntegerField(verbose_name='Subject code')),
                ('Day', models.CharField(choices=[('M', 'Mon'), ('T', 'Tue'), ('W', 'Wed'), ('T', 'Thu'), ('F', 'Fri'), ('S', 'Sat')], max_length=1)),
                ('Time', models.TimeField(verbose_name='Time')),
                ('F_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty Name')),
            ],
        ),
    ]
