# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hod', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Title', models.CharField(max_length=150, verbose_name='Title')),
                ('Type', models.CharField(choices=[('E', 'Educational'), ('S', 'Seminar'), ('W', 'Workshop'), ('C', 'Curriculum Activity'), ('A', 'Admission process'), ('E', 'Exam'), ('R', 'Result')], max_length=1)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('F_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty name')),
                ('HOD_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hod.Hod', verbose_name='Hod name')),
            ],
        ),
    ]
