# Generated by Django 2.1 on 2021-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticebord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='noticeboard',
            name='F_name',
        ),
        migrations.RemoveField(
            model_name='noticeboard',
            name='HOD_name',
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='NoticeBoardimage',
            field=models.ImageField(default=1, upload_to='NoticeBoardimage/'),
            preserve_default=False,
        ),
    ]
