# Generated by Django 2.1 on 2021-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lec_date',
            field=models.DateField(auto_now_add=True, verbose_name='Lecture Date'),
        ),
    ]
