# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('Last_name', models.CharField(max_length=30, verbose_name='Last_name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('Mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('Subject', models.CharField(max_length=30, verbose_name='Subject')),
                ('Messages', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
