# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='Hostel_name',
            field=models.CharField(max_length=30, verbose_name='Hostel name'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='fees',
            field=models.CharField(max_length=3, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='mobile',
            field=models.CharField(max_length=10, verbose_name='Mobile'),
        ),
    ]
