# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
