# Generated by Django 2.1 on 2021-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_item', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
            ],
        ),
    ]
