# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='Food_item',
            field=models.CharField(max_length=30, verbose_name='Food item'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='Price',
            field=models.CharField(max_length=30, verbose_name='Price'),
        ),
    ]
