# Generated by Django 2.1 on 2021-04-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'verbose_name': 'Head of Department'},
        ),
        migrations.AddField(
            model_name='hod',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
