# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile No.')),
                ('a_number', models.CharField(max_length=10, verbose_name='Alt Number')),
                ('Profile_pic', models.ImageField(upload_to='studentimages')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Roll_number', models.IntegerField(verbose_name='Roll number')),
                ('Address', models.TextField(verbose_name='Address')),
                ('DoB', models.DateField(verbose_name='Date of Birth')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Area', verbose_name='Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.City', verbose_name='City')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.State', verbose_name='State name')),
            ],
        ),
    ]
