# Generated by Django 2.1 on 2021-04-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('student', '0003_auto_20210421_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.departments', verbose_name='Departments'),
            preserve_default=False,
        ),
    ]
