# Generated by Django 2.1 on 2021-04-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty'},
        ),
    ]
