# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='Practical_name',
            field=models.CharField(max_length=30, verbose_name='Practical name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Subject',
            field=models.CharField(max_length=30, verbose_name='Subject'),
        ),
    ]
