# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('ass_date', models.DateField(verbose_name='Assign Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('upload', models.FileField(upload_to='studentassignment/')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student')),
            ],
        ),
    ]
