# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='F_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lec_date',
            field=models.DateField(verbose_name='Lecture Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lec_name',
            field=models.CharField(max_length=30, verbose_name='Lecture Name'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student Id'),
        ),
    ]
