# Generated by Django 2.1 on 2021-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContacUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
                ('Messages', models.TextField()),
            ],
        ),
    ]
