# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacus',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='contacus',
            name='Messages',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
