# Generated by Django 2.1 on 2021-03-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0003_auto_20210301_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContacUs',
            new_name='ContactUs',
        ),
    ]
