# Generated by Django 2.1 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fees', models.CharField(max_length=20, verbose_name='Fees')),
                ('semster', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch', verbose_name='Branch')),
            ],
        ),
    ]
