# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Fees',
            field=models.CharField(max_length=20, verbose_name='Fees'),
        ),
    ]
