# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch', verbose_name='Branch'),
        ),
    ]
