# Generated by Django 2.1 on 2021-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evntes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='Title')),
                ('Type', models.CharField(choices=[('E', 'Educational'), ('S', 'Seminar'), ('W', 'Workshop'), ('C', 'Curriculum Activity'), ('A', 'Admission process'), ('E', 'Exam'), ('R', 'Result')], max_length=1)),
                ('NoticeBoardimage', models.ImageField(upload_to='NoticeBoardimage/')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'evntes',
            },
        ),
    ]
