# Generated by Django 2.1 on 2021-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='evntes',
            new_name='Studentevntes',
        ),
        migrations.AlterModelOptions(
            name='studentevntes',
            options={'verbose_name': 'Studentevntes'},
        ),
    ]
