# Generated by Django 2.1 on 2021-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Day',
            field=models.CharField(choices=[('M', 'Mon'), ('T', 'Tue'), ('W', 'Wed'), ('T', 'Thu'), ('F', 'Fri'), ('S', 'Sat')], max_length=1),
        ),
    ]
