# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210226_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Subject_name',
            field=models.CharField(max_length=30, verbose_name='Subject name'),
        ),
    ]
