# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='F_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Sub_code',
            field=models.IntegerField(verbose_name='Subject code'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
