# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.City', verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.State', verbose_name='State name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
