# Generated by Django 2.1 on 2021-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'verbose_name': 'HOD'},
        ),
        migrations.AddField(
            model_name='hod',
            name='Profile_pic',
            field=models.ImageField(default=1, upload_to='HodImages'),
            preserve_default=False,
        ),
    ]
