# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0003_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={},
        ),
        migrations.AlterField(
            model_name='hod',
            name='DoB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='dep',
            field=models.CharField(max_length=15, verbose_name='Department'),
        ),
    ]
