# Generated by Django 2.1 on 2021-02-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hod', '0002_auto_20210226_1149'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Title', models.CharField(max_length=150)),
                ('Type', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('F_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('HOD_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hod.Hod')),
            ],
        ),
    ]
