# Generated by Django 2.1 on 2021-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticebord', '0002_auto_20210226_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='Title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
