# Generated by Django 2.1 on 2021-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticebord', '0003_auto_20210227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='F_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Faculty name'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='HOD_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hod.Hod', verbose_name='Hod name'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
